[package]
name = "rust-lsp-test"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.5"
log = "0.4.22"
lsp-server = "0.7.7"
lsp-types = "0.97.0"
ra_ap_rust-analyzer = "0.0.236"
regex = "1.10.6"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
